export class ProxyModule {
  public static AUTH_USECASES = "AUTH_USECASES";
  public static PRODUCT_USECASES = "PRODUCT_USECASES";
  public static CATEGORY_USECASES = "CATEGORY_USECASES";
  public static RATING_USECASES = "RATING_USECASES";
  public static USER_USECASES = "USER_USECASES";
  public static CART_USECASES = "CART_USECASES";
  public static ORDER_USECASES = "ORDER_USECASES";
  public static STAT_USECASES = "STAT_USECASES";
  public static BANNER_USECASES = "BANNER_USECASES";
  public static SUPPORT_CHAT_USECASES = "SUPPORT_CHAT_USECASES";
}
